server.port: ${PORT:8081}
spring:
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: validate